# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build with travis caches
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: java

jdk:
  - oraclejdk8

#Skipping install step to avoid having Travis run arbitrary './gradlew assemble' task
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install:
  - true

#Don't build tags
branches:
  except:
  - /^v\d/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

#Build and perform release (if needed)
script:
  - ./gradlew build -s && ./gradlew ciPerformRelease

after_script:
  - mv "build/reports/jacoco/test/jacocoTestReport.xml" "src/main/kotlin/jacoco.xml"
  - cd src/main/kotlin/
  - ../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT